/*
 * Scripts that are generated by the console when an account specific
 * agent package is built.
 *
 * These launchers are always written into the package so the download
 * never depends on the availability of a remote asset for the basic
 * install / uninstall entry points.
 */

interface ScriptContext {
  version: string;
  artifactFileName: string;
}

const WINDOWS_INSTALL_PATH =
  "C:\\Program Files\\Kuamini Security Client";

const WINDOWS_EXECUTABLE =
  `${WINDOWS_INSTALL_PATH}\\KuaminiSecurityClient.exe`;

const WINDOWS_RUN_KEY =
  "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run";

export function buildWindowsInstallCommand({
  version,
}: ScriptContext): string {
  return [
    "@echo off",
    "setlocal",
    'set "SCRIPT_DIR=%~dp0"',
    'set "HELPER=%SCRIPT_DIR%install-helper.ps1"',
    `set "AGENT_VERSION=${version}"`,
    'set "CONFIG_DIR=%LOCALAPPDATA%\\KuaminiSecurityClient"',
    `set "AGENT_EXE=${WINDOWS_EXECUTABLE}"`,
    "",
    `echo Kuamini Security Client ${version} - Windows Installer`,
    "echo.",
    "",
    'if not exist "%HELPER%" (',
    "  echo ERROR: install-helper.ps1 was not found next to install-windows.cmd.",
    "  pause",
    "  exit /b 1",
    ")",
    "",
    "rem Seed the account configuration before the agent starts for the first time.",
    'if not exist "%CONFIG_DIR%" mkdir "%CONFIG_DIR%"',
    'if not exist "%CONFIG_DIR%\\config.json" copy /Y "%SCRIPT_DIR%config.json" "%CONFIG_DIR%\\config.json" >nul',
    'copy /Y "%SCRIPT_DIR%registration.token" "%CONFIG_DIR%\\registration.token" >nul',
    "",
    "rem Persist the installed version so the tray menu reports the correct build.",
    `powershell -NoProfile -ExecutionPolicy Bypass -Command "[Environment]::SetEnvironmentVariable('AGENT_VERSION','${version}','Machine')"`,
    "",
    "powershell -NoProfile -ExecutionPolicy Bypass -Command \"Unblock-File -Path '%HELPER%' -ErrorAction SilentlyContinue; & '%HELPER%' %*\"",
    'set "INSTALL_EXIT=%ERRORLEVEL%"',
    "",
    'if not "%INSTALL_EXIT%"=="0" (',
    "  echo.",
    "  echo Installer exited with error code %INSTALL_EXIT%.",
    "  pause",
    "  exit /b %INSTALL_EXIT%",
    ")",
    "",
    "rem Make sure the tray application starts at every logon.",
    `reg add "${WINDOWS_RUN_KEY}" /v KuaminiSecurityClient /t REG_SZ /d "\\"%AGENT_EXE%\\"" /f >nul`,
    "",
    "echo.",
    "echo Installation completed.",
    "echo.",
    "pause",
    "endlocal",
    "",
  ].join("\r\n");
}

export function buildWindowsUninstallCommand(): string {
  return [
    "@echo off",
    "setlocal",
    'set "SCRIPT_DIR=%~dp0"',
    'set "UNINSTALLER=%SCRIPT_DIR%uninstall-kuamini-windows.ps1"',
    "",
    "echo Kuamini Security Client - Windows Uninstaller",
    "echo.",
    "",
    'if not exist "%UNINSTALLER%" (',
    "  echo ERROR: uninstall-kuamini-windows.ps1 was not found.",
    "  pause",
    "  exit /b 1",
    ")",
    "",
    "powershell -NoProfile -ExecutionPolicy Bypass -Command \"Unblock-File -Path '%UNINSTALLER%' -ErrorAction SilentlyContinue; & '%UNINSTALLER%' %*\"",
    'set "UNINSTALL_EXIT=%ERRORLEVEL%"',
    "",
    `reg delete "${WINDOWS_RUN_KEY}" /v KuaminiSecurityClient /f >nul 2>&1`,
    "powershell -NoProfile -ExecutionPolicy Bypass -Command \"[Environment]::SetEnvironmentVariable('AGENT_VERSION',$null,'Machine')\"",
    "",
    'if not "%UNINSTALL_EXIT%"=="0" (',
    "  echo.",
    "  echo Uninstaller exited with error code %UNINSTALL_EXIT%.",
    "  pause",
    "  exit /b %UNINSTALL_EXIT%",
    ")",
    "",
    "echo.",
    "echo Uninstall completed.",
    "echo.",
    "pause",
    "endlocal",
    "",
  ].join("\r\n");
}

export function buildMacInstallCommand({
  version,
  artifactFileName,
}: ScriptContext): string {
  return `#!/bin/bash
# Kuamini Security Client ${version} - macOS installer

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$HOME/.kuamini"
TOKEN="$(tr -d '\\r\\n' < "$SCRIPT_DIR/registration.token")"

export AGENT_VERSION="${version}"

mkdir -p "$CONFIG_DIR"

if [ ! -f "$CONFIG_DIR/config.json" ]; then
  cp "$SCRIPT_DIR/config.json" "$CONFIG_DIR/config.json"
fi

cp "$SCRIPT_DIR/registration.token" "$CONFIG_DIR/registration.token"

if [ -f "$SCRIPT_DIR/install-kuamini-macos.sh" ]; then
  chmod +x "$SCRIPT_DIR/install-kuamini-macos.sh"
  sudo -E AGENT_VERSION="${version}" bash "$SCRIPT_DIR/install-kuamini-macos.sh" "$TOKEN" "$SCRIPT_DIR/${artifactFileName}"
else
  sudo /usr/sbin/installer -pkg "$SCRIPT_DIR/${artifactFileName}" -target /
fi

# Start the tray application immediately after the installation.
open -a "/Applications/KuaminiSecurityClient.app" || true

echo "Installation completed."
`;
}

export function buildMacUninstallCommand(): string {
  return `#!/bin/bash
# Kuamini Security Client - macOS uninstaller

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"

if [ ! -f "$SCRIPT_DIR/uninstall-kuamini-macos.sh" ]; then
  echo "ERROR: uninstall-kuamini-macos.sh was not found." >&2
  exit 1
fi

chmod +x "$SCRIPT_DIR/uninstall-kuamini-macos.sh"
sudo bash "$SCRIPT_DIR/uninstall-kuamini-macos.sh" "$@"

echo "Uninstall completed."
`;
}

export function buildLinuxInstallScript({
  version,
  artifactFileName,
}: ScriptContext): string {
  return `#!/bin/bash
# Kuamini Security Client ${version} - Linux installer

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="/opt/kuamini-security-client"
ARCHIVE="$SCRIPT_DIR/${artifactFileName}"

if [ "$(id -u)" -ne 0 ]; then
  echo "This installer must be run with sudo." >&2
  exit 1
fi

TARGET_USER="\${SUDO_USER:-$(id -un)}"
TARGET_HOME="$(getent passwd "$TARGET_USER" | cut -d: -f6)"
CONFIG_DIR="$TARGET_HOME/.kuamini"
AUTOSTART_DIR="$TARGET_HOME/.config/autostart"

if [ ! -f "$ARCHIVE" ]; then
  echo "ERROR: ${artifactFileName} was not found next to this script." >&2
  exit 1
fi

echo "Installing Kuamini Security Client ${version}..."

rm -rf "$INSTALL_DIR"
mkdir -p "$INSTALL_DIR"
tar -xzf "$ARCHIVE" -C "$INSTALL_DIR" --strip-components=1

install -d -o "$TARGET_USER" "$CONFIG_DIR"

if [ ! -f "$CONFIG_DIR/config.json" ]; then
  install -o "$TARGET_USER" -m 600 "$SCRIPT_DIR/config.json" "$CONFIG_DIR/config.json"
fi

install -o "$TARGET_USER" -m 600 "$SCRIPT_DIR/registration.token" "$CONFIG_DIR/registration.token"

# Autostart the tray application at every login.
install -d -o "$TARGET_USER" "$AUTOSTART_DIR"

cat > "$AUTOSTART_DIR/kuamini-security-client.desktop" <<DESKTOP
[Desktop Entry]
Type=Application
Name=Kuamini Security Client
Exec=env AGENT_VERSION=${version} $INSTALL_DIR/KuaminiSecurityClient
X-GNOME-Autostart-enabled=true
DESKTOP

chown "$TARGET_USER" "$AUTOSTART_DIR/kuamini-security-client.desktop"

# Start the tray application right away for the installing user.
if [ -x "$INSTALL_DIR/KuaminiSecurityClient" ]; then
  sudo -u "$TARGET_USER" AGENT_VERSION="${version}" \\
    nohup "$INSTALL_DIR/KuaminiSecurityClient" >/dev/null 2>&1 &
fi

echo "Installation completed."
`;
}

export function buildLinuxUninstallScript(): string {
  return `#!/bin/bash
# Kuamini Security Client - Linux uninstaller

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"

if [ ! -f "$SCRIPT_DIR/uninstall-kuamini-linux.sh" ]; then
  echo "ERROR: uninstall-kuamini-linux.sh was not found." >&2
  exit 1
fi

chmod +x "$SCRIPT_DIR/uninstall-kuamini-linux.sh"
sudo bash "$SCRIPT_DIR/uninstall-kuamini-linux.sh" "$@"

echo "Uninstall completed."
`;
}

export function buildReadme({
  platform,
  version,
  accountName,
}: {
  platform: "windows" | "macos" | "linux";
  version: string;
  accountName: string;
}): string {
  const header = [
    "Kuamini Security Client",
    `Version : ${version}`,
    `Account : ${accountName}`,
    "",
    "This package is account specific. The registration token it contains",
    "registers the endpoint with the account listed above.",
    "",
  ];

  if (platform === "windows") {
    return [
      ...header,
      "Installation",
      "------------",
      "1. Extract the whole ZIP file to a folder.",
      "2. Right click install-windows.cmd and choose 'Run as administrator'.",
      "   The script installs the MSI, stores the registration token and",
      "   starts the tray application automatically.",
      "",
      "Uninstallation",
      "--------------",
      "Right click uninstall-windows.cmd and choose 'Run as administrator'.",
      "",
      "Files",
      "-----",
      "install-windows.cmd             Installer entry point",
      "install-helper.ps1              Installer implementation",
      "uninstall-windows.cmd           Uninstaller entry point",
      "uninstall-kuamini-windows.ps1   Uninstaller implementation",
      "registration.token              Account registration token",
      "registration_token.txt          Account registration token (alternate name)",
      "config.json                     Account specific agent configuration",
      "",
    ].join("\n");
  }

  if (platform === "macos") {
    return [
      ...header,
      "Installation",
      "------------",
      "1. Extract the whole ZIP file to a folder.",
      "2. Open Terminal in that folder and run:  ./install-macos.command",
      "   (or double click install-macos.command)",
      "   The script installs the package, stores the registration token and",
      "   starts the tray application automatically.",
      "",
      "Uninstallation",
      "--------------",
      "Run ./uninstall-macos.command",
      "",
      "Files",
      "-----",
      "install-macos.command           Installer entry point",
      "install-kuamini-macos.sh        Installer implementation",
      "uninstall-macos.command         Uninstaller entry point",
      "uninstall-kuamini-macos.sh      Uninstaller implementation",
      "registration.token              Account registration token",
      "registration_token.txt          Account registration token (alternate name)",
      "config.json                     Account specific agent configuration",
      "",
    ].join("\n");
  }

  return [
    ...header,
    "Installation",
    "------------",
    "1. Extract the whole ZIP file to a folder.",
    "2. Run:  sudo ./install-kuamini-linux.sh",
    "   The script installs the agent, stores the registration token,",
    "   configures autostart and starts the tray application.",
    "",
    "Uninstallation",
    "--------------",
    "Run ./uninstall-linux.sh",
    "",
    "Files",
    "-----",
    "install-kuamini-linux.sh        Installer",
    "uninstall-linux.sh              Uninstaller entry point",
    "uninstall-kuamini-linux.sh      Uninstaller implementation",
    "registration.token              Account registration token",
    "registration_token.txt          Account registration token (alternate name)",
    "config.json                     Account specific agent configuration",
    "",
  ].join("\n");
}
